---
name: Android CI

on:
  push:
    branches-ignore:
      - dependabot/**
    paths-ignore:
      - LICENSE
      - README.md
      - SECURITY.md
      - CODE_OF_CONDUCT.md
      - .github/**
      - fastlane/*
      - app/proguard-rules.pro
  pull_request:
    path-ignore:
      - LICENSE
      - README.md
      - SECURITY.md
      - CODE_OF_CONDUCT.md
      - .github/workflows/*
      - .github/ISSUE_TEMPLATE/*
      - fastlane/*
      - app/proguard-rules.pro
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: name: Set up JDK 20
      uses: actions/setup-java@v4
      with:
        java-version: '20'
        distribution: 'temurin'
        cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Accept Android SDK licenses
        run: yes | /usr/local/lib/android/sdk/tools/bin/sdkmanager --licenses   
            
      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Upload debug apk
        uses: actions/upload-artifact@v3
        with:
          name: apk-debug
          path: app/build/outputs/apk/debug/app-debug.apk
